version: 1
disable_existing_loggers: false
root:
   level: ${LOG_LEVEL}
   handlers:
   - stderr
   - file_json
   - queue_handler
formatters:
   simple:
      format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S%z'
   json:
      (): tomatempo.logs.JSONFormatter
      fmt_keys:
         level: levelname
         message: message
         timestamp: timestamp
         logger: name
         module: module
         function: funcName
         line: lineno
         thread_name: threadName
handlers:
   stderr:
      class: logging.StreamHandler
      level: WARNING
      formatter: simple
      stream: ext://sys.stdout
   file_json:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: json
      filename: "${LOG_FILE}"
      maxBytes: 100000000
      backupCount: 3
   queue_handler:
      class: logging.handlers.QueueHandler
